apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-java-docker
    image: himanshukla/java-docker
    ports:
    - name: nodejs-port
      containerPort: 3000
