apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: java
spec:
  containers:
  - name: k8s-lrn
    image: himanshukla/java-docker
    ports:
    - name: java-port
      containerPort: 3000
