apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: nginx-himanshu
    image: nginx:1.21.
    ports:
    - containerPort: 8080
  containers:
  - name: watcher-himanshu
    image: afakharany/watcher:latest
