apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld-controller
  labels:
    app: helloworld
spec:
  replicas: 10
  selector:
    matchlabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
     spec:
       containers:
       - name: k8s-demo
         image
